import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PROJETO - 01",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <header className="header-tier">
          <img src="/imagens/logo.svg" alt="Tier 11 Logo" width={120} height={40} className="header-logo" />
          <nav>
            <Link href={"/sobre"}>What we do</Link>
            <Link href={"/blog"}>Blog</Link>
            <Link href={"/podcast"}>Podcast</Link>
            <Link href={"/careers"}>Careers</Link>
            <Link href={"#"} className="cta">Work with us</Link>
          </nav>
        </header>
        {children}
        <footer>
          <ul>
            <li>Instagram</li>
            <li>Facebook</li>
            <li>LinkedIn</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
